{
  "bad": {
    "exception": "[Errno 2] No such file or directory: 'vtk942.yaml'",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/auto_tick.py\", line 776, in _run_migrator_on_feedstock_branch",
      "    migrator_uid, pr_json = run_with_tmpdir(",
      "                            ^^^^^^^^^^^^^^^^",
      "  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/auto_tick.py\", line 488, in run_with_tmpdir",
      "    return run(",
      "           ^^^^",
      "  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/auto_tick.py\", line 566, in run",
      "    migration_run_data = run_migration(",
      "                         ^^^^^^^^^^^^^^",
      "  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/migration_runner.py\", line 82, in run_migration",
      "    return run_migration_local(",
      "           ^^^^^^^^^^^^^^^^^^^^",
      "  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local",
      "    data[\"migrate_return_value\"] = migrator.migrate(",
      "                                   ^^^^^^^^^^^^^^^^^",
      "  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/migrators/migration_yaml.py\", line 433, in migrate",
      "    os.remove(f\"{self.name}.yaml\")",
      "FileNotFoundError: [Errno 2] No such file or directory: 'vtk942.yaml'",
      ""
    ]
  },
  "pre_pr_migrator_attempts": {
    "vtk942": 1
  },
  "pre_pr_migrator_status": {
    "vtk942": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/GITHUB_RUN_ID_NOT_SET\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/auto_tick.py\", line 776, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run_with_tmpdir(\n                            ^^^^^^^^^^^^^^^^\n  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/auto_tick.py\", line 488, in run_with_tmpdir\n    return run(\n           ^^^^\n  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/auto_tick.py\", line 566, in run\n    migration_run_data = run_migration(\n                         ^^^^^^^^^^^^^^\n  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/migration_runner.py\", line 82, in run_migration\n    return run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/Users/janjagusch/Projects/personal/cf-scripts/conda_forge_tick/migrators/migration_yaml.py\", line 433, in migrate\n    os.remove(f\"{self.name}.yaml\")\nFileNotFoundError: [Errno 2] No such file or directory: 'vtk942.yaml'\n"
  }
}